/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as BuyIndexRouteImport } from './routes/buy.index'
import { Route as BuyPaymentRouteImport } from './routes/buy.payment'
import { Route as BuyRecipientRouteImport } from './routes/buy.recipient'
import { Route as BuyReviewRouteImport } from './routes/buy.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIndexRoute = BuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyPaymentRoute = BuyPaymentRouteImport.update({
  id: '/buy/payment',
  path: '/buy/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRecipientRoute = BuyRecipientRouteImport.update({
  id: '/buy/recipient',
  path: '/buy/recipient',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyReviewRoute = BuyReviewRouteImport.update({
  id: '/buy/review',
  path: '/buy/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/buy/payment': typeof BuyPaymentRoute
  '/buy/recipient': typeof BuyRecipientRoute
  '/buy/review': typeof BuyReviewRoute
  '/buy/': typeof BuyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/buy/payment': typeof BuyPaymentRoute
  '/buy/recipient': typeof BuyRecipientRoute
  '/buy/review': typeof BuyReviewRoute
  '/buy': typeof BuyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/buy/payment': typeof BuyPaymentRoute
  '/buy/recipient': typeof BuyRecipientRoute
  '/buy/review': typeof BuyReviewRoute
  '/buy/': typeof BuyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/kyc'
    | '/login'
    | '/register'
    | '/verify'
    | '/buy/payment'
    | '/buy/recipient'
    | '/buy/review'
    | '/buy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/kyc'
    | '/login'
    | '/register'
    | '/verify'
    | '/buy/payment'
    | '/buy/recipient'
    | '/buy/review'
    | '/buy'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/kyc'
    | '/login'
    | '/register'
    | '/verify'
    | '/buy/payment'
    | '/buy/recipient'
    | '/buy/review'
    | '/buy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyRoute: typeof VerifyRoute
  BuyPaymentRoute: typeof BuyPaymentRoute
  BuyRecipientRoute: typeof BuyRecipientRoute
  BuyReviewRoute: typeof BuyReviewRoute
  BuyIndexRoute: typeof BuyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/': {
      id: '/buy/'
      path: '/buy'
      fullPath: '/buy/'
      preLoaderRoute: typeof BuyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/payment': {
      id: '/buy/payment'
      path: '/buy/payment'
      fullPath: '/buy/payment'
      preLoaderRoute: typeof BuyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/recipient': {
      id: '/buy/recipient'
      path: '/buy/recipient'
      fullPath: '/buy/recipient'
      preLoaderRoute: typeof BuyRecipientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/review': {
      id: '/buy/review'
      path: '/buy/review'
      fullPath: '/buy/review'
      preLoaderRoute: typeof BuyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyRoute: VerifyRoute,
  BuyPaymentRoute: BuyPaymentRoute,
  BuyRecipientRoute: BuyRecipientRoute,
  BuyReviewRoute: BuyReviewRoute,
  BuyIndexRoute: BuyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
